package handlers

import (
	"app/database"
	"app/middleware"
	"app/models"
	"context"
	"database/sql"
	"encoding/json"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v4"
)

func actorID(c *fiber.Ctx) string { claims,err:=middleware.ExtractClaims(c);if err!=nil{return ""};return claims.UserID }

func RecordAuditLog(ctx context.Context, actor, action, entityType, entityID string, before, after, metadata map[string]interface{}) error { beforeJSON,_:=json.Marshal(before);afterJSON,_:=json.Marshal(after);metadataJSON,_:=json.Marshal(metadata);_,err:=database.GetDB().Exec(ctx,`INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)`,nullableStringValue(&actor),action,entityType,entityID,beforeJSON,afterJSON,metadataJSON);return err }

func HandleListAuditLogs(c *fiber.Ctx) error {q:=getCatalogListQuery(c,"createdAt",map[string]string{"createdAt":"created_at"});where:=" WHERE 1=1";args:=[]interface{}{};if v:=strings.TrimSpace(c.Query("entityType"));v!=""{where+=" AND entity_type=$"+itoa(len(args)+1);args=append(args,v)};if v:=strings.TrimSpace(c.Query("action"));v!=""{where+=" AND action=$"+itoa(len(args)+1);args=append(args,v)};if q.Search!=""{where+=" AND (entity_id ILIKE $"+itoa(len(args)+1)+" OR entity_type ILIKE $"+itoa(len(args)+1)+")";args=append(args,"%"+q.Search+"%")};db:=database.GetDB();ctx:=context.Background();var total int64;if err:=db.QueryRow(ctx,"SELECT COUNT(*) FROM audit_logs"+where,args...).Scan(&total);err!=nil{return fiber.NewError(500,"failed to count audit logs")};rows,err:=db.Query(ctx,"SELECT id,actor_id,action,entity_type,entity_id,before_data,after_data,metadata,ip_address,user_agent,created_at FROM audit_logs"+where+q.orderBy()+" LIMIT $"+itoa(len(args)+1)+" OFFSET $"+itoa(len(args)+2),append(args,q.PageSize,q.Offset)...);if err!=nil{return fiber.NewError(500,"failed to list audit logs")};defer rows.Close();items:=make([]models.AuditLog,0);for rows.Next(){var item models.AuditLog;var actor,ip,ua sql.NullString;var before,after,metadata []byte;if err:=rows.Scan(&item.ID,&actor,&item.Action,&item.EntityType,&item.EntityID,&before,&after,&metadata,&ip,&ua,&item.CreatedAt);err!=nil{return fiber.NewError(500,"failed to read audit log")};if actor.Valid{item.ActorID=&actor.String};if ip.Valid{item.IPAddress=&ip.String};if ua.Valid{item.UserAgent=&ua.String};item.BeforeData=map[string]interface{}{};item.AfterData=map[string]interface{}{};item.Metadata=map[string]interface{}{};if len(before)>0{_ = json.Unmarshal(before,&item.BeforeData)};if len(after)>0{_ = json.Unmarshal(after,&item.AfterData)};if len(metadata)>0{_ = json.Unmarshal(metadata,&item.Metadata)};items=append(items,item)};return c.JSON(paginatedResponse(items,total,q))}

func HandleListSystemSettings(c *fiber.Ctx) error {q:=getCatalogListQuery(c,"setting_key",map[string]string{"settingKey":"setting_key","updatedAt":"updated_at"});where:="";args:=[]interface{}{};if q.Search!=""{where=" WHERE setting_key ILIKE $1";args=append(args,"%"+q.Search+"%")};db:=database.GetDB();ctx:=context.Background();var total int64;if err:=db.QueryRow(ctx,"SELECT COUNT(*) FROM system_settings"+where,args...).Scan(&total);err!=nil{return fiber.NewError(500,"failed to count system settings")};rows,err:=db.Query(ctx,"SELECT id,setting_key,value_json,updated_by,created_at,updated_at FROM system_settings"+where+q.orderBy()+" LIMIT $"+itoa(len(args)+1)+" OFFSET $"+itoa(len(args)+2),append(args,q.PageSize,q.Offset)...);if err!=nil{return fiber.NewError(500,"failed to list system settings")};defer rows.Close();items:=make([]models.SystemSetting,0);for rows.Next(){var item models.SystemSetting;var value []byte;var updatedBy sql.NullString;if err:=rows.Scan(&item.ID,&item.Key,&value,&updatedBy,&item.CreatedAt,&item.UpdatedAt);err!=nil{return fiber.NewError(500,"failed to read system setting")};item.Value=map[string]interface{}{};_ = json.Unmarshal(value,&item.Value);if updatedBy.Valid{item.UpdatedBy=&updatedBy.String};items=append(items,item)};return c.JSON(paginatedResponse(items,total,q))}

func HandleGetSystemSetting(c *fiber.Ctx) error {var item models.SystemSetting;var value []byte;var updatedBy sql.NullString;err:=database.GetDB().QueryRow(context.Background(),`SELECT id,setting_key,value_json,updated_by,created_at,updated_at FROM system_settings WHERE setting_key=$1`,c.Params("settingKey")).Scan(&item.ID,&item.Key,&value,&updatedBy,&item.CreatedAt,&item.UpdatedAt);if err==pgx.ErrNoRows{return fiber.NewError(404,"system setting not found")};if err!=nil{return fiber.NewError(500,"failed to retrieve system setting")};item.Value=map[string]interface{}{};_ = json.Unmarshal(value,&item.Value);if updatedBy.Valid{item.UpdatedBy=&updatedBy.String};return c.JSON(fiber.Map{"status":"success","success":true,"data":item})}

func HandleUpsertSystemSetting(c *fiber.Ctx) error {var req models.SystemSettingRequest;if err:=c.BodyParser(&req);err!=nil||req.Value==nil{return fiber.NewError(400,"value is required")};value,_:=json.Marshal(req.Value);id:=actorID(c);var item models.SystemSetting;var raw []byte;var updatedBy sql.NullString;err:=database.GetDB().QueryRow(context.Background(),`INSERT INTO system_settings(setting_key,value_json,updated_by) VALUES($1,$2,$3) ON CONFLICT(setting_key) DO UPDATE SET value_json=EXCLUDED.value_json,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING id,setting_key,value_json,updated_by,created_at,updated_at`,c.Params("settingKey"),value,nullableStringValue(&id)).Scan(&item.ID,&item.Key,&raw,&updatedBy,&item.CreatedAt,&item.UpdatedAt);if err!=nil{return fiber.NewError(500,"failed to save system setting")};item.Value=req.Value;if updatedBy.Valid{item.UpdatedBy=&updatedBy.String};return c.JSON(fiber.Map{"status":"success","success":true,"data":item})}

func HandleDeleteSystemSetting(c *fiber.Ctx) error {result,err:=database.GetDB().Exec(context.Background(),`DELETE FROM system_settings WHERE setting_key=$1`,c.Params("settingKey"));if err!=nil{return fiber.NewError(500,"failed to delete system setting")};if result.RowsAffected()==0{return fiber.NewError(404,"system setting not found")};return c.SendStatus(204)}

func HandleListSyncLogs(c *fiber.Ctx) error {merchantID,err:=getMerchantIDFromClaims(c);if err!=nil{return err};q:=getCatalogListQuery(c,"createdAt",map[string]string{"createdAt":"created_at"});where:=" WHERE merchant_id=$1";args:=[]interface{}{merchantID};if v:=strings.TrimSpace(c.Query("deviceId"));v!=""{where+=" AND device_id=$2";args=append(args,v)};db:=database.GetDB();ctx:=context.Background();var total int64;if err:=db.QueryRow(ctx,"SELECT COUNT(*) FROM sync_logs"+where,args...).Scan(&total);err!=nil{return fiber.NewError(500,"failed to count sync logs")};rows,err:=db.Query(ctx,"SELECT id,merchant_id,device_id,total_sales,successful_syncs,failed_syncs,error_message,created_at FROM sync_logs"+where+q.orderBy()+" LIMIT $"+itoa(len(args)+1)+" OFFSET $"+itoa(len(args)+2),append(args,q.PageSize,q.Offset)...);if err!=nil{return fiber.NewError(500,"failed to list sync logs")};defer rows.Close();items:=make([]models.SyncLog,0);for rows.Next(){var item models.SyncLog;var device,errorMessage sql.NullString;if err:=rows.Scan(&item.ID,&item.MerchantID,&device,&item.TotalSales,&item.SuccessfulSyncs,&item.FailedSyncs,&errorMessage,&item.CreatedAt);err!=nil{return fiber.NewError(500,"failed to read sync log")};if device.Valid{item.DeviceID=&device.String};if errorMessage.Valid{item.ErrorMessage=&errorMessage.String};items=append(items,item)};return c.JSON(paginatedResponse(items,total,q))}
